# Generated by Django 5.2.6 on 2025-09-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_productimage_product_condition_and_more'),
    ]

    operations = [
    ]
